"""
Local rebuild of data/data.js — mirrors write_data_js() in core/github_store.py
but reads all files from disk instead of GitHub.

Usage:
    python rebuild_data_js.py

Safe to run anytime. Does NOT touch state.json or history.json.
"""
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent

def read(path: str, default="") -> str:
    try:
        return (ROOT / path).read_text(encoding="utf-8")
    except Exception:
        return default

def read_jsonl(path: str, last_n: int = 50) -> list:
    try:
        lines = (ROOT / path).read_text(encoding="utf-8").splitlines()
        entries = []
        for l in lines:
            l = l.strip()
            if l:
                try:
                    entries.append(json.loads(l))
                except Exception:
                    pass
        return entries[-last_n:]
    except Exception:
        return []

def js_str(s: str) -> str:
    return json.dumps(s or "")

state   = json.loads(read("data/state.json",   "{}"))
history = json.loads(read("data/history.json", "{}"))
cfg     = json.loads(read("data/config.json",  "{}"))

draft_json   = json.dumps(state.get("draft_picks", []), indent=2, ensure_ascii=False)
state_json   = json.dumps(state,   indent=2, ensure_ascii=False)
history_json = json.dumps(history, indent=2, ensure_ascii=False)

scout_skills_text  = read("skills/scout_skills.md")
commit_skills_text = read("skills/commit_skills.md")
analyst_notes_text = read("skills/analyst_notes.md")
analyst_rules_text = read("skills/analyst_rules.md")

analyst_log = read_jsonl("audit/analyst_log.jsonl")
scout_log   = read_jsonl("audit/scout_log.jsonl")
commit_log  = read_jsonl("audit/commit_log.jsonl")
settler_log = read_jsonl("audit/settler_log.jsonl")
audit_log   = sorted(
    analyst_log + scout_log + commit_log + settler_log,
    key=lambda e: e.get("ts", "")
)

ts = datetime.now(timezone.utc).isoformat()

content = f"""// Auto-generated by Tobias agents -- do not edit manually
// Last updated: {ts}

const STATE_DATA = {state_json};
const HISTORY_DATA = {history_json};
const DRAFT_PICKS = {draft_json};
const SCOUT_STATUS = {js_str(state.get('scout_status', 'pending'))};
const SCOUT_ERROR = {js_str(state.get('scout_error', ''))};
const SCOUT_UPDATED_AT = {js_str(state.get('scout_updated_at') or '')};
const COMMIT_STATUS = {js_str(state.get('commit_status', 'pending'))};
const COMMIT_UPDATED_AT = {js_str(state.get('commit_updated_at') or '')};
const LLM_PROVIDER = {js_str(state.get('llm_provider', 'claude'))};
const CONFIG_DATA = {json.dumps(cfg, indent=2, ensure_ascii=False)};
const SCOUT_SKILLS = {js_str(scout_skills_text)};
const COMMIT_SKILLS = {js_str(commit_skills_text)};
const ANALYST_RULES = {js_str(analyst_rules_text)};
const AUDIT_LOG = {json.dumps(audit_log, ensure_ascii=False)};
const ANALYST_NOTES = {js_str(analyst_notes_text)};
"""

out = ROOT / "data/data.js"
out.write_text(content, encoding="utf-8")
print(f"data.js written ({len(content):,} bytes)")
print(f"  state: game={state.get('game')} bankroll={state.get('bankroll')}")
print(f"  history entries: {len(history.get('entries', []))}")
print(f"  audit entries: {len(audit_log)}")
print(f"  draft picks: {len(state.get('draft_picks', []))}")
